//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PapaBobsPizza.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class PizzaPrice
    {
        public int Id { get; set; }
        public decimal SmallPizzaPrice { get; set; }
        public decimal MediumPizzaPrice { get; set; }
        public decimal LargePizzaPrice { get; set; }
        public decimal RegularPizzaPrice { get; set; }
        public decimal ThinPizzaPrice { get; set; }
        public decimal ThickPizzaPrice { get; set; }
        public decimal SausagePrice { get; set; }
        public decimal PepperoniPrice { get; set; }
        public decimal OnionsPrice { get; set; }
        public decimal GreenPeppersPrice { get; set; }
    }
}
